# This is a basic workflow to help you get started with Actions

name: Folder

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
        - uses: actions/checkout@v3  #super importante
        - name: Folder
        
          run: |
            pwd
            echo "hola"

            echo "ahora github"
            ls ./.github/plan # path correcto
