name: Terraform Plan

on:
  pull_request:

env:
  TF_SA: github-deployments@sam-gallagher-tutorials-001.iam.gserviceaccount.com
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"

  ARM_CLIENT_ID: "0eba58bf-9f11-4836-98b9-def160de2a51" # This doesn't have to be a secret. Client IDs are not sensitive.
  ARM_CLIENT_SECRET: "6Ev8Q~20SNO2xXANk2_lmRWeR5fV3SRahz_MBcs9"
  ARM_SUBSCRIPTION_ID: "4d000790-f279-46d9-811e-45f8ddf9a3aa"
  ARM_TENANT_ID: "2bd38efa-c424-4fff-9fff-bfe89a641b09"

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    if: github.event.review.state != 'approved'
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}

        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Plan
        uses: ./.github/plan
        with:
          terraform_directory: "./.terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: "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"
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
